### ISSUE TITLE
Adding "Firefox ESR" to query results in 0%

### ISSUE THREAD

**Issue by defx** [PSPDFKit-labs/browserslist.dev#52]
Steps to repro:

1. try query like `last 2 versions and > 0.5% and not dead` and see coverage as expected (~76%)
2. append "and Firefox ESR" and see coverage drop to 0%

**Comment by Lagicrus** [comment]
Can confirm this broke my query

**Comment by ritz078** [comment]
What is the expected output here?

If I run `npx browserslist "last 2 versions and > 0.5% and not dead and Firefox ESR"`, I do not get any browser. Am I missing something?

**Comment by Dreamsorcerer** [comment]
Looks expected to me. This works fine: `last 100 versions and > 0% and not dead and Firefox ESR`
First issue is that Firefox 91 is at 0.1%, which is less than 0.5%. Second issue is that Firefox 91 is not in the last 2 versions of Firefox.

Maybe Firefox ESR should be considered separate from Firefox, so that `last 2 versions` will still pick up the current ESR releases, but that'd be an issue for https://github.com/browserslist/browserslist

**Comment by marek-saji** [comment]
> What is the expected output here?
> 
> If I run `npx browserslist "last 2 versions and > 0.5% and not dead and Firefox ESR"`, I do not get any browser. Am I missing something?

You probably want to use `last 2 versions and > 0.5% and not dead, Firefox ESR` as in:

- find browsers that match
  - being two last versions
  - have market share of >0.5%
  - are not dead
- also, add Firefox ESR

**Comment by miguelcalderon** [comment]
Working as expected, closing.
